try:   
    print(i)        # NameError: name 'i' is not defined
except:
    print("Caught Exception!!!")